traps:
  - id: trap-db-prod-01
    template: text/prod_db_config.json.j2
    output: db_production.json
    category: credential
    format: text
    priority: critical

  - id: trap-aws-root-01
    template: text/aws_credentials.txt.j2
    output: .aws/credentials
    category: credential
    format: text
    priority: critical

  - id: trap-env-prod-01
    template: text/env.prod.j2
    output: .env.production
    category: config
    format: text
    priority: medium

  - id: trap-docker-01
    template: text/docker-compose.yml.j2
    output: docker-compose.yml
    category: config
    format: text
    priority: low

  - id: trap-vpn-corp-01
    template: text/vpn_client.ovpn.j2
    output: corporate_vpn.ovpn
    category: credential
    format: text
    priority: medium

  - id: trap-doc-finance-01
    template: binary/payroll_template.docx
    output: Salary_Report_Q4_2024.docx
    category: document
    format: binary
    priority: high

  - id: trap-xls-pass-01
    template: binary/passwords_template.xlsx
    output: Server_Passwords.xlsx
    category: credential
    format: binary
    priority: critical

