# Манифест ловушек: учётные данные и ключи
traps:
  - id: trap-aws-root-01
    template: text/aws_credentials.txt.j2
    output: .aws/credentials
    category: credential
    format: text
    priority: critical

  - id: trap-ssh-key-01
    template: text/ssh_private_key.j2
    output: .ssh/id_rsa_prod
    category: credential
    format: text
    priority: critical

  - id: trap-ssh-key-02
    template: text/ssh_private_key.j2
    output: .ssh/deploy_key
    category: credential
    format: text
    priority: critical

  - id: trap-git-creds-01
    template: text/git_credentials.j2
    output: .git-credentials
    category: credential
    format: text
    priority: high

  - id: trap-npmrc-01
    template: text/npmrc.j2
    output: .npmrc
    category: credential
    format: text
    priority: high

  - id: trap-xls-pass-01
    template: binary/passwords_template.xlsx
    output: Server_Passwords.xlsx
    category: credential
    format: binary
    priority: critical

  - id: trap-vpn-corp-01
    template: text/vpn_client.ovpn.j2
    output: corporate_vpn.ovpn
    category: credential
    format: text
    priority: high
